export const employees = [
  {
    id: "emp001",
    empCode: "RVK123",
    name: "Ravi Kumar",
    phone: "9876543210",
    email: "ravi@company.com",
    address: "123 Main Street, City",
    position: "Packer",
    departmentId: "packing",
    hourlyRate: 150,
    barcodeId: "RVK123",
    joinDate: "2024-01-15",
    status: "active",
  },
  {
    id: "emp002",
    empCode: "PRS456",
    name: "Prashant Singh",
    phone: "9876543211",
    email: "prashant@company.com",
    address: "456 Oak Avenue, City",
    position: "Production Worker",
    departmentId: "production",
    hourlyRate: 160,
    barcodeId: "PRS456",
    joinDate: "2024-01-20",
    status: "active",
  },
  {
    id: "emp003",
    empCode: "AMS789",
    name: "Anita Sharma",
    phone: "9876543212",
    email: "anita@company.com",
    address: "789 Pine Road, City",
    position: "Quality Inspector",
    departmentId: "quality",
    hourlyRate: 180,
    barcodeId: "AMS789",
    joinDate: "2024-02-01",
    status: "active",
  },
  {
    id: "emp004",
    empCode: "SKM101",
    name: "Suresh Kumar",
    phone: "9876543213",
    email: "suresh@company.com",
    address: "101 Elm Street, City",
    position: "Maintenance Technician",
    departmentId: "maintenance",
    hourlyRate: 170,
    barcodeId: "SKM101",
    joinDate: "2024-02-10",
    status: "active",
  },
  {
    id: "emp005",
    empCode: "RKL202",
    name: "Rakesh Lal",
    phone: "9876543214",
    email: "rakesh@company.com",
    address: "202 Maple Drive, City",
    position: "Loader",
    departmentId: "loading",
    hourlyRate: 140,
    barcodeId: "RKL202",
    joinDate: "2024-02-15",
    status: "active",
  },
  {
    id: "emp006",
    empCode: "PKS303",
    name: "Pooja Kumari",
    phone: "9876543215",
    email: "pooja@company.com",
    address: "303 Cedar Lane, City",
    position: "Senior Packer",
    departmentId: "packing",
    hourlyRate: 165,
    barcodeId: "PKS303",
    joinDate: "2024-03-01",
    status: "active",
  },
]
